import { Experience, Venture, Thesis } from './types'

export const experiences: Experience[] = [
  {
    id: 'wellhub',
    company: 'Wellhub (Gympass)',
    role: 'Partnerships & Growth Associate',
    location: 'Madrid, Spain (Germany Market)',
    dateRange: 'May 2025 - Nov 2025',
    bullets: [
      'Supported expansion of B2B partnerships in the DE market by managing outreach, partner coordination, and onboarding activities',
      'Implemented CRM workflow improvements to make partner tracking and reporting more consistent',
      'Conducted market and competitor analysis to support regional partnership planning and growth efforts',
    ],
    keyImpact: [
      'Improved partnership execution through more structured outreach, tracking, and follow-up processes',
      'Contributed to growth efforts by combining partner support with systems-focused process improvements'
    ],
    logo: '/logos/wellhub.png',
    tags: ['Partnerships', 'Growth'],
    type: 'Partnerships',
  },
  {
    id: 'mars',
    company: 'Mars Wrigley',
    role: 'Strategy & Execution Associate',
    location: 'Dubai, UAE',
    dateRange: 'Jul 2024 - Dec 2024',
    bullets: [
      'Built KPI dashboards in Power BI to track sales and digital performance across 4 Gulf markets',
      'Prepared category and performance analysis to support portfolio reviews and GTM planning',
      'Helped standardize reporting frameworks across regional teams to improve visibility and consistency',
    ],
    keyImpact: [
      'Improved decision support through clearer dashboards, reporting structures, and performance tracking',
      'Contributed to strategy discussions through structured analysis and reporting insights'
    ],
    logo: '/logos/mars.png',
    tags: ['Strategy', 'Analytics'],
    type: 'Strategy',
  },
  {
    id: 'deloitte',
    company: 'Deloitte',
    role: 'Business Process Solutions (Intern)',
    location: 'Sharjah, UAE',
    dateRange: 'Sep 2023 - Jan 2024',
    bullets: [
      'Built reporting pipelines in Power BI and SQL to improve data organization and reporting quality',
      'Supported client workstreams by preparing analysis, documentation, and reporting inputs for project teams',
      'Delivered benchmarking and process analysis that informed operational improvement recommendations',
    ],
    keyImpact: [
      'Strengthened reporting reliability through structured data preparation and analysis support',
      'Contributed to process optimization work through benchmarking, reporting, and problem-solving'
    ],
    logo: '/logos/deloitte.png',
    tags: ['Consulting', 'Process Design'],
    type: 'Strategy',
  },
  {
    id: 'digital-qatalyst',
    company: 'Digital Qatalyst DMCC',
    role: 'Technology Analyst',
    location: 'Dubai, UAE',
    dateRange: 'Feb 2024 - Apr 2024',
    bullets: [
      'Implemented APQC process frameworks across Finance, HR, and Legal to improve process clarity and alignment',
      'Supported CRM and ERP workflow improvements to streamline internal operations and data handling',
      'Designed a structured onboarding system to improve the new-hire experience and completion flow',
    ],
    keyImpact: [
      'Improved process consistency through workflow standardization across core business functions',
      'Helped strengthen onboarding and internal systems through more structured operational design'
    ],
    logo: '/logos/digital-qatalyst.jpeg',
    tags: ['Operations', 'Process Design'],
    type: 'Tech',
  },
  {
    id: 'teleperformance',
    company: 'Teleperformance',
    role: 'Operations Intern',
    location: 'Dubai, UAE',
    dateRange: 'Aug 2022 - Mar 2023',
    bullets: [
      'Monitored client KPIs and flagged operational gaps for follow-up with internal teams',
      'Supported monthly Power BI reporting to improve visibility across account performance',
      'Prepared reporting insights for client accounts including MedCare and Majid Al Futtaim',
    ],
    keyImpact: [
      'Supported more consistent operational reporting and account tracking through regular dashboard updates',
    ],
    logo: '/logos/teleperformance.png',
    tags: ['Operations', 'Analytics'],
    type: 'Ops',
  },
  {
    id: 'facts',
    company: 'Facts Computer House',
    role: 'Business Development Intern',
    location: 'Dubai, UAE',
    dateRange: 'Jun 2021 - Aug 2021',
    bullets: [
      'Supported development of internal HR and accounting modules using Python, Java, and C',
      'Assisted with custom software solutions for client payment and business process needs',
    ],
    keyImpact: [
      'Contributed to client-facing software work by supporting practical business process solutions',
    ],
    logo: '/logos/facts.jpeg',
    tags: ['Development', 'B2B'],
    type: 'Ops',
  },
]

export const ventures: Venture[] = [
  {
    id: 'blyza',
    name: 'Blyza Entertainment',
    role: 'Founder & CEO',
    badge: 'Founder',
    status: 'Live',
    summary: 'Building an entertainment ecosystem across digital and real-world experiences.',
    description: 'Parent company spanning PlayBlyza and Jeggy, focused on consumer engagement and scalable product ecosystems.',
    tags: ['EntertainmentTech', 'Gaming', 'SaaS'],
    highlights: [
      { label: 'Scale', value: '50,000+ users across 90+ countries on PlayBlyza.' },
      { label: 'Tech', value: 'React/Next.js, Firebase/Firestore, Vercel, custom APIs.' },
      { label: 'Business Model', value: 'B2C subscriptions + B2B licensing + events + sponsorships.' },
    ],
    links: {
      caseStudy: '/case-studies/blyza',
      website: 'https://joinblyza.com',
      demo: 'https://jeggy.app',
    },
    logo: '/logos/blyza.png',
    year: '2025 - Present',
    images: [
      '/ventures/blyza/shot-1.jpg',
      '/ventures/blyza/shot-2.jpg',
      '/ventures/blyza/shot-3.jpg',
    ],
    verticalStatuses: [
      { name: 'PlayBlyza', status: 'Live' },
      { name: 'Jeggy', status: 'Live' },
    ],
  },
  {
    id: 'fpp',
    name: 'FPP Entertainment',
    role: 'Founder & Events Director',
    badge: 'Founder',
    status: 'Live',
    summary: 'Premium live shows and dance-led productions across Dubai landmarks.',
    description: 'Produced shows at Burj Khalifa & Palazzo Versace Hotel (dance-led; large venue ops). Partnerships, logistics, creative direction.',
    tags: ['Events', 'Production', 'Partnerships'],
    highlights: [
      { label: 'Venues', value: 'Produced at Burj Khalifa and Palazzo Versace Hotel.' },
      { label: 'Operations', value: 'Owned logistics, vendor management, creative direction.' },
      { label: 'Partnerships', value: 'Brand/sponsor collaborations for large-format events.' },
    ],
    logo: '/logos/fpp.png',
    year: '2022 - 2024',
    images: [
      '/ventures/fpp/shot-1.jpg',
      '/ventures/fpp/shot-2.jpg',
    ],
  },
  {
    id: 'kirushibumi',
    name: 'KiruShibumi',
    role: 'Founder',
    badge: 'Founder',
    status: 'Paused',
    summary: 'Online apparel brand using Printify and lean e-commerce ops.',
    description: 'Online clothing brand with Printify; e-com ops & performance marketing',
    tags: ['E-commerce', 'Brand', 'Growth'],
    highlights: [
      { label: 'Model', value: 'On-demand fulfillment and SKU testing.' },
      { label: 'Marketing', value: 'Influencer and social campaigns for conversion.' },
      { label: 'Creative', value: 'Hands-on brand/creative direction.' },
    ],
    links: {
      caseStudy: '/case-studies/kirushibumi',
    },
    logo: '/logos/kirushibumi.jpeg',
    year: '2023',
    images: [
      '/ventures/kirushibumi/shot-1.jpg',
    ],
  },
  {
    id: 'paragon',
    name: 'Paragon Events',
    role: 'Operations & Marketing Support',
    badge: 'Support',
    status: 'Live',
    summary: 'Operations, vendor coordination, and client servicing for corporate and lifestyle events in Dubai.',
    description: 'Vendor coordination, on-site logistics, sponsorship assistance',
    tags: ['Events', 'Operations', 'Marketing'],
    highlights: [
      { label: 'Logistics', value: 'On-site logistics and scheduling across multi-vendor productions.' },
      { label: 'Sponsorship', value: 'Sponsorship support and fulfillment for partner brands.' },
      { label: 'Creative', value: 'Creative campaign assistance and client communications.' },
    ],
    logo: '/logos/paragon.jpg',
    year: '2024 - Present',
    images: [
      '/ventures/paragon/shot-1.jpg',
    ],
    clickUrl: 'https://ParagonEventsDubai.com',
    clickLabel: 'Visit Website',
  },
  {
    id: 'layl',
    name: 'LAYL',
    role: 'Founder (Concept)',
    badge: 'Support',
    status: 'Paused',
    summary: 'Tourism & media discovery concept for Dubai (paused pre-launch).',
    description: 'Tourism & media discovery app for Dubai (paused pre-launch)',
    tags: ['Tourism', 'Media', 'Concept'],
    highlights: [
      { label: 'Research', value: 'Market and user research to identify discovery gaps.' },
      { label: 'Prototype', value: 'Prototype exploration for content + local experiences.' },
      { label: 'Status', value: 'Paused pre-launch; learnings inform future builds.' },
    ],
    logo: '/logos/layl.png',
    year: '2023 - 2024',
    images: [
      '/ventures/layl/shot-1.jpg',
    ],
  },
]

export const theses: Thesis[] = [
  {
    slug: 'entertainment-as-a-service',
    title: 'Entertainment-as-a-Service',
    abstract: 'The convergence of venue operations, content production, and sponsorship creates a sustainable entertainment flywheel with multiple revenue streams and built-in moats.',
    tags: ['Entertainment', 'Business Model', 'Events'],
    category: 'Market Thesis',
    publishedAt: '2024-11-01',
  },
  {
    slug: 'ai-team-building',
    title: 'AI in Team-Building (HRTech)',
    abstract: 'AI-powered engagement platforms can transform corporate team-building from one-off events into continuous, data-driven culture initiatives with measurable ROI.',
    tags: ['HRTech', 'AI', 'B2B SaaS'],
    category: 'Technology Thesis',
    publishedAt: '2024-10-15',
  },
  {
    slug: 'gamified-learning',
    title: 'Gamified Corporate Learning',
    abstract: 'Gamification in L&D drives 3x higher engagement and retention vs traditional methods. The market is shifting from compliance training to experience-first skill development.',
    tags: ['EdTech', 'HRTech', 'Gamification'],
    category: 'Market Thesis',
    publishedAt: '2024-09-20',
  },
  {
    slug: 'wellness-ecosystems-emea',
    title: 'Wellness Ecosystems (EMEA)',
    abstract: 'EMEA wellness market is fragmented with strong local players. Winners will be aggregators who unlock cross-vertical synergies (fitness + mental health + nutrition).',
    tags: ['Wellness', 'Marketplaces', 'EMEA'],
    category: 'Market Thesis',
    publishedAt: '2024-08-10',
  },
  {
    slug: 'creator-commerce',
    title: 'Creator-Commerce Infrastructure',
    abstract: 'The next wave of creator tools will focus on infrastructure (payments, fulfillment, analytics) rather than distribution, enabling creators to own their entire value chain.',
    tags: ['Creator Economy', 'Infrastructure', 'E-commerce'],
    category: 'Technology Thesis',
    publishedAt: '2024-07-05',
  },
  {
    slug: 'irl-game-shows',
    title: 'Real-world Game Shows as IRL Social Products',
    abstract: 'Physical game show experiences combine the virality of digital content with the premium pricing of experiential entertainment, creating hybrid social products.',
    tags: ['Entertainment', 'Social', 'IRL'],
    category: 'Market Thesis',
    publishedAt: '2024-06-15',
  },
]
