import { Experience, Venture, Thesis } from './types'

export const experiences: Experience[] = [
  {
    id: 'wellhub',
    company: 'Wellhub (Gympass)',
    role: 'Partnerships & Growth Associate',
    location: 'Madrid, Spain (Germany Market)',
    dateRange: 'May 2025 - Nov 2025',
    bullets: [
      'Expanded B2B partnerships in DE market, onboarding 15+ wellness brands and increasing partner conversion by 18%',
      'Built automated CRM workflows that cut manual partner reporting time by 30%',
      'Ran competitive and market analysis that informed a regional growth strategy driving 12% higher acquisition',
    ],
    keyImpact: [
      'Automated partner workflows, saving 10+ hrs/week in manual ops',
      'Scaled partnership pipeline by 3x through structured outreach systems'
    ],
    logo: '/logos/wellhub.png',
    tags: ['Partnerships', 'Growth'],
    type: 'Partnerships',
  },
  {
    id: 'mars',
    company: 'Mars Wrigley',
    role: 'Strategy & Execution Associate',
    location: 'Dubai, UAE',
    dateRange: 'Jul 2024 - Dec 2024',
    bullets: [
      'Built KPI dashboards (Power BI) tracking sales and digital performance across 4 Gulf markets',
      'Delivered category segmentation analysis that shaped a $2M+ portfolio strategy',
      'Created scalable reporting frameworks adopted by 3 regional teams, reducing reporting cycles by 40%',
    ],
    keyImpact: [
      'Reduced reporting cycle time by 40% through automated dashboards',
      'Insights directly influenced $2M+ GTM allocation decisions'
    ],
    logo: '/logos/mars.png',
    tags: ['Strategy', 'Analytics'],
    type: 'Strategy',
  },
  {
    id: 'deloitte',
    company: 'Deloitte',
    role: 'Business Process Solutions (Intern)',
    location: 'Sharjah, UAE',
    dateRange: 'Sep 2023 - Jan 2024',
    bullets: [
      'Built automated reporting pipelines (Power BI, SQL) improving data accuracy by 25%',
      'Supported digital transformation initiatives across 2 client engagements',
      'Delivered benchmarking analysis that informed process optimization recommendations',
    ],
    keyImpact: [
      'Improved data reliability by 25% through automated pipelines',
      'Contributed to process optimization across multiple client projects'
    ],
    logo: '/logos/deloitte.png',
    tags: ['Consulting', 'Process Design'],
    type: 'Strategy',
  },
  {
    id: 'digital-qatalyst',
    company: 'Digital Qatalyst DMCC',
    role: 'Technology Analyst',
    location: 'Dubai, UAE',
    dateRange: 'Feb 2024 - Apr 2024',
    bullets: [
      'Implemented APQC process frameworks across Finance, HR, and Legal, reducing process gaps by 30%',
      'Automated CRM/ERP workflows that cut manual data entry by 50%',
      'Designed gamified onboarding system, increasing new-hire completion rates by 35%',
    ],
    keyImpact: [
      'Cut manual data entry by 50% through CRM/ERP automation',
      'Increased onboarding completion by 35% with gamified systems'
    ],
    logo: '/logos/digital-qatalyst.jpeg',
    tags: ['Automation', 'Process Design'],
    type: 'Tech',
  },
  {
    id: 'teleperformance',
    company: 'Teleperformance',
    role: 'Operations Intern',
    location: 'Dubai, UAE',
    dateRange: 'Aug 2022 - Mar 2023',
    bullets: [
      'Monitored client KPIs with 95% accuracy, identifying and resolving operational shortfalls',
      'Automated monthly reporting using Power BI, cutting manual effort by 20%',
      'Delivered insights that improved decision-making for MedCare and Majid Al Futtaim accounts',
    ],
    keyImpact: [
      'Reduced manual reporting time by 20% with Power BI automation',
    ],
    logo: '/logos/teleperformance.png',
    tags: ['Operations', 'Analytics'],
    type: 'Ops',
  },
  {
    id: 'facts',
    company: 'Facts Computer House',
    role: 'Business Development Intern',
    location: 'Dubai, UAE',
    dateRange: 'Jun 2021 - Aug 2021',
    bullets: [
      'Built HR and accounting modules using Python, Java, and C',
      'Resolved B2B payment process bottlenecks through custom software solutions',
    ],
    keyImpact: [
      'Delivered custom payment solutions for B2B clients',
    ],
    logo: '/logos/facts.jpeg',
    tags: ['Development', 'B2B'],
    type: 'Ops',
  },
]

export const ventures: Venture[] = [
  {
    id: 'blyza',
    name: 'Blyza Entertainment',
    role: 'Founder & CEO',
    badge: 'Founder',
    status: 'Live',
    summary: 'Built an entertainment ecosystem across gaming and real-world experiences with three verticals: PlayBlyza.com (Live), Blyza Live (In development), and Jeggy (R&D).',
    description: 'Multi-vertical ecosystem: PlayBlyza.com (online party games), Blyza Live (TV-style game-show venue), Jeggy (B2B team-building SaaS)',
    tags: ['EntertainmentTech', 'SaaS', 'Gaming', 'Events'],
    highlights: [
      { label: 'Scale', value: '50,000+ games played across 90+ countries on PlayBlyza.' },
      { label: 'Tech', value: 'React/Next.js, Firebase/Firestore, Vercel, custom APIs.' },
      { label: 'Roadmap', value: 'Blyza Live (In development), Jeggy (R&D) - B2B team-building SaaS.' },
      { label: 'Business Model', value: 'B2C subscriptions + B2B licensing + events + sponsorships.' },
    ],
    links: {
      caseStudy: '/case-studies/blyza',
      website: 'https://joinblyza.com',
    },
    logo: '/logos/blyza.png',
    year: '2025 - Present',
    images: [
      '/ventures/blyza/shot-1.jpg',
      '/ventures/blyza/shot-2.jpg',
      '/ventures/blyza/shot-3.jpg',
    ],
    verticalStatuses: [
      { name: 'PlayBlyza', status: 'Live' },
      { name: 'Blyza Live', status: 'In development' },
      { name: 'Jeggy', status: 'R&D' },
    ],
  },
  {
    id: 'fpp',
    name: 'FPP Entertainment',
    role: 'Founder & Events Director',
    badge: 'Founder',
    status: 'Live',
    summary: 'Premium live shows and dance-led productions across Dubai landmarks.',
    description: 'Produced shows at Burj Khalifa & Palazzo Versace Hotel (dance-led; large venue ops). Partnerships, logistics, creative direction.',
    tags: ['Events', 'Production', 'Partnerships'],
    highlights: [
      { label: 'Venues', value: 'Produced at Burj Khalifa and Palazzo Versace Hotel.' },
      { label: 'Operations', value: 'Owned logistics, vendor management, creative direction.' },
      { label: 'Partnerships', value: 'Brand/sponsor collaborations for large-format events.' },
    ],
    logo: '/logos/fpp.png',
    year: '2022 - 2024',
    images: [
      '/ventures/fpp/shot-1.jpg',
      '/ventures/fpp/shot-2.jpg',
    ],
  },
  {
    id: 'kirushibumi',
    name: 'KiruShibumi',
    role: 'Founder',
    badge: 'Founder',
    status: 'Paused',
    summary: 'Online apparel brand using Printify and lean e-commerce ops.',
    description: 'Online clothing brand with Printify; e-com ops & performance marketing',
    tags: ['E-commerce', 'Brand', 'Growth'],
    highlights: [
      { label: 'Model', value: 'On-demand fulfillment and SKU testing.' },
      { label: 'Marketing', value: 'Influencer and social campaigns for conversion.' },
      { label: 'Creative', value: 'Hands-on brand/creative direction.' },
    ],
    links: {
      caseStudy: '/case-studies/kirushibumi',
    },
    logo: '/logos/kirushibumi.jpeg',
    year: '2023',
    images: [
      '/ventures/kirushibumi/shot-1.jpg',
    ],
  },
  {
    id: 'paragon',
    name: 'Paragon Events',
    role: 'Operations & Marketing Support',
    badge: 'Support',
    status: 'Live',
    summary: 'Operations, vendor coordination, and client servicing for corporate and lifestyle events in Dubai.',
    description: 'Vendor coordination, on-site logistics, sponsorship assistance',
    tags: ['Events', 'Operations', 'Marketing'],
    highlights: [
      { label: 'Logistics', value: 'On-site logistics and scheduling across multi-vendor productions.' },
      { label: 'Sponsorship', value: 'Sponsorship support and fulfillment for partner brands.' },
      { label: 'Creative', value: 'Creative campaign assistance and client communications.' },
    ],
    logo: '/logos/paragon.jpg',
    year: '2024 - Present',
    images: [
      '/ventures/paragon/shot-1.jpg',
    ],
    clickUrl: 'https://ParagonEventsDubai.com',
    clickLabel: 'Visit Website',
  },
  {
    id: 'layl',
    name: 'LAYL',
    role: 'Founder (Concept)',
    badge: 'R&D',
    status: 'R&D',
    summary: 'Tourism & media discovery concept for Dubai (paused pre-launch).',
    description: 'Tourism & media discovery app for Dubai (paused pre-launch)',
    tags: ['Tourism', 'Media', 'R&D'],
    highlights: [
      { label: 'Research', value: 'Market and user research to identify discovery gaps.' },
      { label: 'Prototype', value: 'Prototype exploration for content + local experiences.' },
      { label: 'Status', value: 'Paused pre-launch; learnings inform future builds.' },
    ],
    logo: '/logos/layl.png',
    year: '2023 - 2024',
    images: [
      '/ventures/layl/shot-1.jpg',
    ],
  },
]

export const theses: Thesis[] = [
  {
    slug: 'entertainment-as-a-service',
    title: 'Entertainment-as-a-Service',
    abstract: 'The convergence of venue operations, content production, and sponsorship creates a sustainable entertainment flywheel with multiple revenue streams and built-in moats.',
    tags: ['Entertainment', 'Business Model', 'Events'],
    category: 'Market Thesis',
    publishedAt: '2024-11-01',
  },
  {
    slug: 'ai-team-building',
    title: 'AI in Team-Building (HRTech)',
    abstract: 'AI-powered engagement platforms can transform corporate team-building from one-off events into continuous, data-driven culture initiatives with measurable ROI.',
    tags: ['HRTech', 'AI', 'B2B SaaS'],
    category: 'Technology Thesis',
    publishedAt: '2024-10-15',
  },
  {
    slug: 'gamified-learning',
    title: 'Gamified Corporate Learning',
    abstract: 'Gamification in L&D drives 3x higher engagement and retention vs traditional methods. The market is shifting from compliance training to experience-first skill development.',
    tags: ['EdTech', 'HRTech', 'Gamification'],
    category: 'Market Thesis',
    publishedAt: '2024-09-20',
  },
  {
    slug: 'wellness-ecosystems-emea',
    title: 'Wellness Ecosystems (EMEA)',
    abstract: 'EMEA wellness market is fragmented with strong local players. Winners will be aggregators who unlock cross-vertical synergies (fitness + mental health + nutrition).',
    tags: ['Wellness', 'Marketplaces', 'EMEA'],
    category: 'Market Thesis',
    publishedAt: '2024-08-10',
  },
  {
    slug: 'creator-commerce',
    title: 'Creator-Commerce Infrastructure',
    abstract: 'The next wave of creator tools will focus on infrastructure (payments, fulfillment, analytics) rather than distribution, enabling creators to own their entire value chain.',
    tags: ['Creator Economy', 'Infrastructure', 'E-commerce'],
    category: 'Technology Thesis',
    publishedAt: '2024-07-05',
  },
  {
    slug: 'irl-game-shows',
    title: 'Real-world Game Shows as IRL Social Products',
    abstract: 'Physical game show experiences combine the virality of digital content with the premium pricing of experiential entertainment, creating hybrid social products.',
    tags: ['Entertainment', 'Social', 'IRL'],
    category: 'Market Thesis',
    publishedAt: '2024-06-15',
  },
]
